[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@account-abstraction/contracts/=lib/account-abstraction/contracts/'
    ]

[rpc_endpoints]
linea-testnet = "${LINEA_GOERLI_RPC_URL}"
base-goerli = "${BASE_GOERLI_RPC_URL}"
scroll-sepolia = "${SCROLL_SEPOLIA_RPC_URL}"

[etherscan]
base-goerli = { key = "${ETHERSCAN_API_KEY}", chain = 84531, url = "https://api-goerli.basescan.org/api" }
base = { key = "${BASE_ETHERSCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }
linea-testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.lineascan.build/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
