[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@account-abstraction/contracts/=lib/account-abstraction/contracts/'
    ]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
base-goerli = "${BASE_GOERLI_RPC_URL}"
linea-testnet = "${LINEA_GOERLI_RPC_URL}"
scroll-sepolia = "${SCROLL_SEPOLIA_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}", chain = 5 }
base-goerli = { key = "${ETHERSCAN_API_KEY}", chain = 84531 }
linea-testnet = { key = "${LINEASCAN_API_KEY}", chain = 59140 }
scroll-sepolia = { key = "${SCROLLSCAN_API_KEY}", url = "https://api-sepolia.scrollscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
